

const DATA_PRODUCTs = [
    { "id": 1,
      "name": "IPhone 15 Pro Max 256GB",
      "shortname": "Ip15ProMax",
      "price": 34990000,
      "ctg_id": 1,
      "product_related_id": 1,
      "img_src": "https://cdn2.cellphones.com.vn/x/media/catalog/product/v/n/vn_iphone_15_pro_blue_titanium_pdp_image_position-1b_blue_titanium_color.jpg",
      "thumb_src": "https://cdn2.cellphones.com.vn/x/media/catalog/product/v/n/vn_iphone_15_pro_blue_titanium_pdp_image_position-1b_blue_titanium_color.jpg",
      "purchased": 1,
      "quantity": 1,
      "is_featured": 1,
      "is_public": 1,
      "img_id": 1,
      "prot_attr_grp_id": 1,
      "supplier_id": 1,
      "discount_id": 1,
      "short_description": "Super Retina XDR Display. Full-screen OLED display 6.7 inches (diagonal)...",
      "description": "Super Retina XDR Display. Full-screen OLED display 6.7 inches (diagonal). Resolution of 2796x1290 pixels with a pixel density of 460 ppi. The iPhone 15 Pro Max display has beautifully rounded corners that follow a standard rectangular shape. When measured as a standard rectangular shape, the screen size is 6.69 inches diagonally (actual display area is smaller). Main Camera 48MP: 24 mm, ƒ/1.78 aperture, second-generation optical image stabilization, 100% Focus Pixels, supports ultra-high-resolution photos (24MP and 48MP)\nUltra Wide Camera 12MP: 13 mm, ƒ/2.2 aperture and 120° field of view, 100% Focus Pixels\nTelephoto 2x 12MP (supported by quad-pixel sensor): 48 mm, ƒ/1.78 aperture, second-generation optical image stabilization, 100% Focus Pixels\nTelephoto 5x 12MP: 120 mm, ƒ/2.8 aperture, 3D optical image stabilization and autofocus, tetraprism design\n5x optical zoom, 2x optical zoom out; optical zoom range up to 10x. Digital zoom up to 25x"
    },
    
    {
      "id": 2,
      "name": "IPhone 14 Pro Max 128GB",
      "shortname": "Ip14ProMax",
      "price": 27390000,
      "ctg_id": 1,
      "product_related_id": 1,
      "img_src": "https://sieuthiserver.vn/wp-content/uploads/2022/10/iphone-14-pro-bac-1-2.jpg",
      "thumb_src": "https://sieuthiserver.vn/wp-content/uploads/2022/10/iphone-14-pro-bac-1-2.jpg",
      "purchased": 1,
      "quantity": 1,
      "is_featured": 1,
      "is_public": 1,
      "img_id": 2,
      "prot_attr_grp_id": 1,
      "supplier_id": 2,
      "discount_id": 2,
      "short_description": "Up to now, OLED panels have always been highly appreciated by the user community when appearing on Apple product lines,...",
      "description": "Up to now, OLED panels have always been highly appreciated by the user community when appearing on Apple product lines, with the iPhone 14 Pro Max this is no exception when the images that the device brings are complete. genuine power. The screen resolution reaches 2796 x 1290 Pixels, so reproducing highly detailed images is very easy. Phenomena like screen pitting are something I have never seen appear on the phone in 2 weeks. experience."
    },
    
    {
      "id": 3,
      "name": "Samsung Galaxy S23 Ultra 5G 256GB",
      "shortname": "SamsungGalaxyS23",
      "price": 20590000,
      "ctg_id": 1,
      "product_related_id": 1,
      "img_src": "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/s/2/s23-ultra-xanh-1_3_1.png",
      "thumb_src": "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/s/2/s23-ultra-xanh-1_3_1.png",
      "purchased": 1,
      "quantity": 1,
      "is_featured": 1,
      "is_public": 1,
      "img_id": 3,
      "prot_attr_grp_id": 1,
      "supplier_id": 3,
      "discount_id": 3,
      "short_description": "Galaxy S23 Ultra made a strong impression upon launch with its groundbreaking design...",
      "description": "Galaxy S23 Ultra made a strong impression upon launch with its groundbreaking design and outstanding performance. In late March 2024, Samsung introduced One UI 6.1, bringing to the Galaxy S23 Ultra advanced AI features from the previous Galaxy S24 series. In terms of design, the Samsung Galaxy S23 Ultra will continue to inherit the luxurious design from the previous generation, still with a metal frame, glass back and slightly curved shape on the sides and screen. As for the edges around the device, the Galaxy S23 Ultra is surrounded by a frame made from aluminum with durable, sturdy properties and extremely effectively optimized weight. This frame is made in a glossy style, helping the device add a striking highlight to the design. The feeling when touching the frame is like being covered with a layer of glossy plating around it, so this will not be an easy place to scratch as some users suspect."
    },
    
    {
      "id": 4,
      "name": "Lenovo Legion 9 16IRX8 83AG0047VN Gaming Laptop",
      "shortname": "Lenovo Legion9",
      "price": 136000000,
        "ctg_id": 2,
        "product_related_id": 2,
      "img_src": "https://product.hstatic.net/200000722513/product/83ag0047vn_b57e907d045e448b9845f3754b097d5d_grande.png",
      "thumb_src": "https://product.hstatic.net/200000722513/product/83ag0047vn_b57e907d045e448b9845f3754b097d5d_grande.png",
      "purchased": 1,
      "quantity": 1,
      "is_featured": 1,
      "is_public": 1,
      "img_id": 4,
      "prot_attr_grp_id": 2,
      "supplier_id": 4,
      "discount_id": 4,
      "short_description": "The Lenovo Legion 9 16IRX8 83AG0047VN is meticulously crafted right from its exterior...",
      "description": "The Lenovo Legion 9 16IRX8 83AG0047VN is meticulously crafted right from its exterior. A standout innovation on the Legion 9 is the application of an 8-layer hard pressing method to create a tough and durable shell layer that is 10% more durable than traditional aluminum materials. Premium carbon material makes the newcomer to Lenovo's lineup uniquely distinctive with a lid featuring unique patterns and textures. Liquid cooling technology on the Lenovo Legion 9 laptop brings a revolutionary first in the world. Breakthrough with rapid cooling ability on a premium gaming laptop. Meet the demands of gaming graphics cards and high-intensity work smoothly. Maintain cool operation for gamers to confidently engage in peak gaming. The Lenovo Legion 9 with its powerful configuration including an Intel Core i9-13980HX CPU with 24 cores and 32 threads, 64GB DDR5 RAM operating at 6400MHz speed, and a 2TB M.2 PCIe 4.0x4 NVMe SSD, along with the NVIDIA GeForce RTX 4090 GPU, is a powerhouse. This powerful CPU enables smooth multitasking and high-performance demanding applications. Large and high-speed RAM ensures stable performance while working with multiple applications simultaneously."
    },
    
    
    {
      "id": 5,
      "name": "Samsung Odyssey NEO G9 LS57CG952 57 4K 240Hz Curved Monitor",
      "shortname": "Samsung Neo G9 Curved Monitor",
      "price": 59990000,
        "ctg_id": 2,
        "product_related_id": 2,
      "img_src": "https://product.hstatic.net/200000722513/product/vn-odyssey-neo-g9-g95nc-ls57cg952nexxv-537933911_3923e3e9cf374fafb9ead3a36151d0e4_grande.png",
      "thumb_src": "https://product.hstatic.net/200000722513/product/vn-odyssey-neo-g9-g95nc-ls57cg952nexxv-537933911_3923e3e9cf374fafb9ead3a36151d0e4_grande.png",
      "purchased": 1,
      "quantity": 1,
      "is_featured": 1,
      "is_public": 1,
      "img_id": 5,
      "prot_attr_grp_id": 2,
      "supplier_id": 5,
      "discount_id": 5,
      "short_description": "The Samsung Odyssey NEO G9 LS57CG952 57 4K 240Hz Curved Monitor brings gaming to life more vividly than reality itself...",
      "description": "The Samsung Odyssey NEO G9 LS57CG952 57 4K 240Hz Curved Monitor brings gaming to life more vividly than reality itself. The world's first Dual UHD monitor envelops your field of view with a super-wide 57-inch screen and a 1000R curvature. Designed to meet the needs of gamers and multimedia enthusiasts alike, this monitor not only delivers stunning visual experiences but also optimizes performance. With a high refresh rate, accurate color display, and integrated eye protection technology, you'll never want to take your eyes off this screen! The power of Quantum Mini-LED and VESA Display HDR IM1000 delivers astonishingly accurate image precision, detail, and brightness at every level. Even the smallest details are incredibly lifelike. Quantum Mini-LED technology helps reproduce more accurate colors and better contrast, providing a vivid and sharp image experience. Meanwhile, VESA Display HDR IM1000 ensures that you can see every detail in scenes of both light and dark, from deep blacks to bright highlights. This not only makes the image more realistic but also allows you to enjoy every moment with optimal brightness."
    },
    
    
    {
      "id": 6,
      "name": "Wrinkle-Free Coffee Fiber Long-Sleeve Shirt WRINKLE FREE 13",
      "shortname": "Wrinkle-Free Shirt WRINKLE FREE 13",
      "price": 327000,
        "ctg_id": 3,
        "product_related_id": 3,
      "img_src": "https://cdn2.yame.vn/pimg/ao-so-mi-tay-dai-soi-ca-phe-wrinkle-free-13-0022478/5dd41ed7-c24b-9500-193e-001ad35b1a68.jpg?w=540&h=756",
      "thumb_src": "https://cdn2.yame.vn/pimg/ao-so-mi-tay-dai-soi-ca-phe-wrinkle-free-13-0022478/5dd41ed7-c24b-9500-193e-001ad35b1a68.jpg?w=540&h=756",
      "purchased": 1,
      "quantity": 1,
      "is_featured": 1,
      "is_public": 1,
      "img_id": 6,
      "prot_attr_grp_id": 3,
      "supplier_id": 6,
      "discount_id": 6,
      "short_description": "Material: Coffee Fiber (CAFÉ FABRIC)...",
      "description": "Material: Coffee Fiber (CAFÉ FABRIC). Composition: 50% Coffee, 50% Polyester, Odor Control, Fast Drying, Ice Cool Touch, UV Protection"
    },
    
    
      {
        "id": 7,
        "name": "Men's Premium Slim Fit Cotton Solid Color Chino Pants - 10S24PCA002P",
        "shortname": "Men's Chino Pants 10S24PCA002P",
        "price": 638000,
        "ctg_id": 3,
        "product_related_id": 3,
        "img_src": "https://routine.vn/media/catalog/product/cache/5b5632a96492396f42c72e22fdd64763/q/u/quan-kaki-nam-02-10s24pca002p_black-_7__1_1.jpg",
      "thumb_src": "https://routine.vn/media/catalog/product/cache/5b5632a96492396f42c72e22fdd64763/q/u/quan-kaki-nam-02-10s24pca002p_black-_7__1_1.jpg",
      "purchased": 1,
      "quantity": 1,
      "is_featured": 1,
      "is_public": 1,
      "img_id": 7,
      "prot_attr_grp_id": 3,
      "supplier_id": 7,
      "discount_id": 7,
        "short_description": "Fit: Slim, Gender: Men, Material: Cotton,...",
        "description": "Fit: Slim, Gender: Men, Material: Cotton, Design: Solid Color, Pocket Style: Slant Pocket"
      },
    
      {
        "id": 8,
        "name": "Women's Wide Leg Pleated Pocketed Solid Color Fabric Pants - 10S24PFOW002",
        "shortname": "Women's Fabric Pants 10S24PFOW002",
        "price": 569000,
        "ctg_id": 3,
        "product_related_id": 3,
        "img_src": "https://routine.vn/media/amasty/webp/catalog/product/cache/5b5632a96492396f42c72e22fdd64763/q/u/quan-vai-nu-ong-rong-2-10s24pfow002_oyster_gray_1__3_1_jpg.webp",
      "thumb_src": "https://routine.vn/media/amasty/webp/catalog/product/cache/5b5632a96492396f42c72e22fdd64763/q/u/quan-vai-nu-ong-rong-2-10s24pfow002_oyster_gray_1__3_1_jpg.webp",
      "purchased": 1,
      "quantity": 1,
      "is_featured": 1,
      "is_public": 1,
      "img_id": 8,
      "prot_attr_grp_id": 3,
      "supplier_id": 8,
      "discount_id": 8,
        "short_description": "Fit: Wide Leg, Gender: Women,...",
        "description": "Fit: Wide Leg, Gender: Women, Material: Polyester, Design: Solid Color, Pocket Style: Slant Pocket"
      },
    
    {
      "id": 9,
      "name": "ASUS ROG STRIX RTX4090-O24G GAMING 24GB GDDR6X Graphics Card",
      "shortname": "ASUS RTX4090 24GB",
      "price": 69990000,
        "ctg_id": 2,
        "product_related_id": 2,
      "img_src": "https://lh3.googleusercontent.com/FWmpP-jeT_lyYA40Q9MQqM2nYNueBmejtwAnrOSNriZMuaAjkIYPknqbcr6Ctrk3CQZM34nKnBDY7v3REbhYJEvZCVG873Y=w500-rw",
      "thumb_src": "https://lh3.googleusercontent.com/FWmpP-jeT_lyYA40Q9MQqM2nYNueBmejtwAnrOSNriZMuaAjkIYPknqbcr6Ctrk3CQZM34nKnBDY7v3REbhYJEvZCVG873Y=w500-rw",
      "purchased": 1,
      "quantity": 1,
      "is_featured": 1,
      "is_public": 1,
      "img_id": 9,
      "prot_attr_grp_id": 2,
      "supplier_id": 9,
      "discount_id": 9,
      "short_description": "Brand: ASUS, Warranty: 36 months...",
      "description": "Brand: ASUS, Warranty: 36 months. Chipset Manufacturer: NVIDIA. Graphics Chip Series: GeForce RTX 40 series. Model: ROG STRIX RTX4090-O24G GAMING. Part-number: 90YV0ID0-M0NM00. GPU: GeForce RTX 4090. Memory: 24GB GDDR6X (21 Gbps / 384-bit). Series: ROG. GPU clock: Boost Clock (OC mode): 2640 MHz."
    },
    
    {
      "id": 10,
      "name": "Weilaiya Truffle Multi-Layer Repair Shampoo and Conditioner Set",
      "shortname": "Weilaiya Truffle Shampoo & Conditioner",
      "price": 1170000,
        "ctg_id": 4,
        "product_related_id": 4,
      "img_src": "https://sieuthilamdep.com/images/ab__webp/thumbnails/435/537/detailed/15/bo-dau-goi-xa-phuc-hoi-da-tang-nam-truffle-weilaiya.jpg_jpg.webp",
      "thumb_src": "https://sieuthilamdep.com/images/ab__webp/thumbnails/435/537/detailed/15/bo-dau-goi-xa-phuc-hoi-da-tang-nam-truffle-weilaiya.jpg_jpg.webp",
      "purchased": 1,
      "quantity": 1,
      "is_featured": 1,
      "is_public": 1,
      "img_id": 10,
      "prot_attr_grp_id": 4,
      "supplier_id": 10,
      "discount_id": 10,
      "short_description": "The Weilaiya Truffle Multi-Layer Repair Shampoo and Conditioner Set is a premium line designed specifically for hair salons...",
      "description": "The Weilaiya Truffle Multi-Layer Repair Shampoo and Conditioner Set is a premium line designed specifically for hair salons. It breaks conventional patterns and establishes a completely new concept of hair care: Shampoo not only cleanses but also rejuvenates and fights aging of the scalp. A healthy scalp is essential for strong and healthy hair. This meticulously crafted set invests in quality, fragrance, color, and packaging. The highlight of this premium product lies in its 'superfood' ingredients, which contain an abundance of nutrients and rare elements that elevate hair and scalp care to a whole new level. Using 'superfoods' in beauty products is a trend among renowned global cosmetics brands."
    },
    
    {
      "id": 11,
      "name": "Lolita Round Toe Strap Cross High Heel Platform Shoes PU Leather D1528 White Size 35",
      "shortname": "Lolita High Heel Shoes D1528 White Size 35",
      "price": 627000,
        "ctg_id": 5,
        "product_related_id": 5,
      "img_src": "https://admin.thegioigiay.com/upload/product/2024/05/giay-lolita-mui-tron-quai-ngang-nhun-de-dup-cao-3-5cm-da-pu-d1528-mau-trang-size-35-66336336672f9-02052024165606.jpg",
      "thumb_src": "https://admin.thegioigiay.com/upload/product/2024/05/giay-lolita-mui-tron-quai-ngang-nhun-de-dup-cao-3-5cm-da-pu-d1528-mau-trang-size-35-66336336672f9-02052024165606.jpg",
      "purchased": 1,
      "quantity": 1,
      "is_featured": 1,
      "is_public": 1,
      "img_id": 11,
      "prot_attr_grp_id": 5,
      "supplier_id": 11,
      "discount_id": 11,
      "short_description": "The Lolita Round Toe Strap Cross High Heel Platform Shoes D1528 are adorable and stylish shoes suitable for girls who love cute and quirky styles...",
      "description": "The Lolita Round Toe Strap Cross High Heel Platform Shoes D1528 are adorable and stylish shoes suitable for girls who love cute and quirky styles. Made from PU leather, these shoes provide softness and comfort to your feet while ensuring durability and easy cleaning. The round toe design and cross strap add a cute and feminine touch to the shoes. The platform sole with a height of 3-5cm adds extra height while maintaining comfort for walking. With their unique and eye-catching style, these shoes are the perfect accent for any of your outfits. Whether you're strolling around the city, going on a date, or attending events, these Lolita shoes will make you stand out and feel confident."
    },
    
    {
      "id": 12,
      "name": "DSQUARED2 Men's Cyprus Bomber Jacket",
      "shortname": "DSQUARED2 Cyprus Bomber Jacket",
      "price": 57000000,
        "ctg_id": 3,
        "product_related_id": 3,
      "img_src": "https://product.hstatic.net/1000284478/product/900_s74am1411_2_753c819ba2f6481bae6b187d3b698eaf_large.jpg",
      "thumb_src": "https://product.hstatic.net/1000284478/product/900_s74am1411_2_753c819ba2f6481bae6b187d3b698eaf_large.jpg",
      "purchased": 1,
      "quantity": 1,
      "is_featured": 1,
      "is_public": 1,
      "img_id": 12,
      "prot_attr_grp_id": 3,
      "supplier_id": 12,
      "discount_id": 12,
      "short_description": "Design: Ribbed cuffs and hem...",
      "description": "Design: Ribbed cuffs and hem. Logo detail on the left sleeve. Soft fabric, provides good warmth. Modern color tone, easy to match with various outfits and accessories. Logo: Prominent logo detail on the back. Fit: Comfortable and relaxed fit. Pockets: Two slant pockets. Zipper: Zip closure. Suitable for occasions: Casual outings, work...Seasonal trend: Suitable for all seasons"
    },
    
    {
      "id": 13,
      "name": "Gucci GG Supreme Baseball Cap With Feline Head In Neutrals Size M",
      "shortname": "Gucci GG Supreme Baseball Cap",
      "price": 36000000,
        "ctg_id": 6,
        "product_related_id": 6,
      "img_src": "https://cdn.vuahanghieu.com/unsafe/0x500/left/top/smart/filters:quality(90)/https://admin.vuahanghieu.com/upload/product/2023/01/mu-gucci-gg-supreme-supreme-baseball-cap-with-feline-head-in-neutrals-size-m-63b3cdc3a458a-03012023134003.jpg",
      "thumb_src": "https://cdn.vuahanghieu.com/unsafe/0x500/left/top/smart/filters:quality(90)/https://admin.vuahanghieu.com/upload/product/2023/01/mu-gucci-gg-supreme-supreme-baseball-cap-with-feline-head-in-neutrals-size-m-63b3cdc3a458a-03012023134003.jpg",
      "purchased": 1,
      "quantity": 1,
      "is_featured": 1,
      "is_public": 1,
      "img_id": 13,
      "prot_attr_grp_id": 6,
      "supplier_id": 13,
      "discount_id": 13,
      "short_description": "The cap is made of Canvas/leather material,...",
      "description": "The cap is made of Canvas/leather material, providing a cool and comfortable feeling for the wearer. The stitching of the cap is meticulous and precise, impressing even the most discerning customers. The Gucci logo on the cap creates a very unique focal point. At the back of the cap, you can adjust the size to fit your head circumference. The neutral black color of the cap is easy to match with various outfits according to your preference."
    },
    
    
    {
      "id": 14,
      "name": "Initio Parfums Prives Initio Addictive Vibration EDP",
      "shortname": "Initio Parfums Perfume",
      "price": 6787000,
        "ctg_id": 7,
        "product_related_id": 7,
      "img_src": "https://www.thegioinuochoa.com.vn/uploads/item_product/thumb1500x500/202305/230503_200230_186805.png",
      "thumb_src": "https://www.thegioinuochoa.com.vn/uploads/item_product/thumb1500x500/202305/230503_200230_186805.png",
      "purchased": 1,
      "quantity": 1,
      "is_featured": 1,
      "is_public": 1,
      "img_id": 14,
      "prot_attr_grp_id": 7,
      "supplier_id": 14,
      "discount_id": 14,
      "short_description": "Released in 2016 in France - the capital of the world's top perfumes,...",
      "description": "Released in 2016 in France - the capital of the world's top perfumes, Initio Addictive Vibration EDP is a mesmerizing blend of floral fragrances. Under the hands of Pierre-Constanin Guéros and Maurice Roucel, the scent of Initio Addictive Vibration EDP becomes a beautiful melody with enchanting notes that anyone would want to savor. DESIGN OF INITIO ADDICTIVE VIBRATION EDP\nThe perfume brand Initio Parfums Prives released its first product in 2015, with two collections: Magnetic Blend and Absolutes. Initio Parfums Prives owns fragrances that are elegant and hidden in bottles with simple yet exquisite designs. Initio Addictive Vibration EDP features a traditional design, quite simple, adorned with a powerful, distinctive black coat, creating initial attraction before you immerse yourself in the sweet floral scent. INITIO ADDICTIVE VIBRATION EDP - SWEET FLORAL MELODY\nWhat fragrances does Initio Addictive Vibration EDP have? Initio Addictive Vibration EDP takes us to the atmosphere of spring. The fragrance begins with a combination of orange blossom and apple blossom. If the apple blossom brings a gentle melody, the orange blossom brings a bit of freshness, light sweetness, and vitality. That blend becomes richer thanks to the presence of warm golden honey, the pleasant sweetness of vanilla, and the tranquility of musk, blending seamlessly together. The soft and sweet fragrances blend together, delicately lingering on the skin."
    },
    
    
    {
      "id": 15,
      "name": "Devialet Gemini II Opera de Paris Earphones",
      "shortname": "Devialet Gemini II Airpods",
      "price": 17890000,
        "ctg_id": 8,
        "product_related_id": 8,
      "img_src": "https://antien.vn/files/styles/pslide/public/products/photos/2023/10/16/tai-nghe-devialet-gemini-ii.jpg?itok=ap4_ESXq",
      "thumb_src": "https://antien.vn/files/styles/pslide/public/products/photos/2023/10/16/tai-nghe-devialet-gemini-ii.jpg?itok=ap4_ESXq",
      "purchased": 1,
      "quantity": 1,
      "is_featured": 1,
      "is_public": 1,
      "img_id": 15,
      "prot_attr_grp_id": 8,
      "supplier_id": 15,
      "discount_id": 15,
      "short_description": "Adaptive active noise cancellation technology (Devialet Adaptive Noise Cancellation)...",
      "description": "Adaptive active noise cancellation technology (Devialet Adaptive Noise Cancellation). With 10mm titanium drivers.Multi-device connection.Noise-filtering technology on the microphone enhances call quality. Bluetooth 5.2 connectivity. With 5-hour battery life, up to 22 hours combined with the case. Qi wireless charging compatible case. IPX4 water resistance."
    },
    
    {
      "id": 16,
      "name": "Tissot Men's Watch T086.408.22.036.00 Size 41mm",
      "shortname": "Tissot Men's Watch",
      "price": 19000000,
        "ctg_id": 9,
        "product_related_id": 9,
      "img_src": "https://www.watchstore.vn/images/products/others/2024/large/dong-ho-tissot-t086-408-22-036-00_1-ims-1712565982.webp",
      "thumb_src": "https://www.watchstore.vn/images/products/others/2024/large/dong-ho-tissot-t086-408-22-036-00_1-ims-1712565982.webp",
      "purchased": 1,
      "quantity": 1,
      "is_featured": 1,
      "is_public": 1,
      "img_id": 16,
      "prot_attr_grp_id": 9,
      "supplier_id": 16,
      "discount_id": 16,
      "short_description": "The Tissot T086.408.22.036.00 is truly a 41mm men's Powermatic 80 Chronometer watch,...",
      "description": "The Tissot T086.408.22.036.00 is truly a 41mm men's Powermatic 80 Chronometer watch, with a thickness of 9.8mm, fitting snugly on the wrists of men with a circumference of 16cm or more. With its silver-tone stainless steel design complemented by gold accents on the bezel, this 3-hand, 1-date watch is extremely suitable for sophisticated gentlemen or confident office workers. The Tissot T086.408.22.036.00 dial is impressive. On the youthful white dial of the watch is an impressive 2-layered face. The central circle features Stick hands and a date window at the familiar 3 o'clock position, making it easy for users to check the date. The outer circle is adorned with 12 diamond hour markers, enhancing the watch's elegant and sophisticated beauty."
    },
    
    
];

const DATA_PRODUCT = [
  {
  "id": 1,
  "name": "IPhone 15 Pro Max 256GB",
  "shortname": "Ip15ProMax",
  "price": 34990000,
  "ctg_id": 1,
  "product_related_id": 1,
  "img_src": "https://cdn2.cellphones.com.vn/x/media/catalog/product/v/n/vn_iphone_15_pro_blue_titanium_pdp_image_position-1b_blue_titanium_color.jpg",
  "thumb_src": "https://cdn2.cellphones.com.vn/x/media/catalog/product/v/n/vn_iphone_15_pro_blue_titanium_pdp_image_position-1b_blue_titanium_color.jpg",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 1,
  "prot_attr_grp_id": 1,
  "supplier_id": 1,
  "discount_id": 1,
  "short_description": "Super Retina XDR Display. Full-screen OLED display 6.7 inches (diagonal)...",
  "description": "Super Retina XDR Display. Full-screen OLED display 6.7 inches (diagonal). Resolution of 2796x1290 pixels with a pixel density of 460 ppi. The iPhone 15 Pro Max display has beautifully rounded corners that follow a standard rectangular shape. When measured as a standard rectangular shape, the screen size is 6.69 inches diagonally (actual display area is smaller). Main Camera 48MP: 24 mm, ƒ/1.78 aperture, second-generation optical image stabilization, 100% Focus Pixels, supports ultra-high-resolution photos (24MP and 48MP)\nUltra Wide Camera 12MP: 13 mm, ƒ/2.2 aperture and 120° field of view, 100% Focus Pixels\nTelephoto 2x 12MP (supported by quad-pixel sensor): 48 mm, ƒ/1.78 aperture, second-generation optical image stabilization, 100% Focus Pixels\nTelephoto 5x 12MP: 120 mm, ƒ/2.8 aperture, 3D optical image stabilization and autofocus, tetraprism design\n5x optical zoom, 2x optical zoom out; optical zoom range up to 10x. Digital zoom up to 25x"
},

{
  "id": 2,
  "name": "IPhone 14 Pro Max 128GB",
  "shortname": "Ip14ProMax",
  "price": 27390000,
  "ctg_id": 1,
  "product_related_id": 1,
  "img_src": "https://sieuthiserver.vn/wp-content/uploads/2022/10/iphone-14-pro-bac-1-2.jpg",
  "thumb_src": "https://sieuthiserver.vn/wp-content/uploads/2022/10/iphone-14-pro-bac-1-2.jpg",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 2,
  "prot_attr_grp_id": 1,
  "supplier_id": 2,
  "discount_id": 2,
  "short_description": "Up to now, OLED panels have always been highly appreciated by the user community when appearing on Apple product lines,...",
  "description": "Up to now, OLED panels have always been highly appreciated by the user community when appearing on Apple product lines, with the iPhone 14 Pro Max this is no exception when the images that the device brings are complete. genuine power. The screen resolution reaches 2796 x 1290 Pixels, so reproducing highly detailed images is very easy. Phenomena like screen pitting are something I have never seen appear on the phone in 2 weeks. experience."
},

{
  "id": 3,
  "name": "Samsung Galaxy S23 Ultra 5G 256GB",
  "shortname": "SamsungGalaxyS23",
  "price": 20590000,
  "ctg_id": 1,
  "product_related_id": 1,
  "img_src": "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/s/2/s23-ultra-xanh-1_3_1.png",
  "thumb_src": "https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/s/2/s23-ultra-xanh-1_3_1.png",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 3,
  "prot_attr_grp_id": 1,
  "supplier_id": 3,
  "discount_id": 3,
  "short_description": "Galaxy S23 Ultra made a strong impression upon launch with its groundbreaking design...",
  "description": "Galaxy S23 Ultra made a strong impression upon launch with its groundbreaking design and outstanding performance. In late March 2024, Samsung introduced One UI 6.1, bringing to the Galaxy S23 Ultra advanced AI features from the previous Galaxy S24 series. In terms of design, the Samsung Galaxy S23 Ultra will continue to inherit the luxurious design from the previous generation, still with a metal frame, glass back and slightly curved shape on the sides and screen. As for the edges around the device, the Galaxy S23 Ultra is surrounded by a frame made from aluminum with durable, sturdy properties and extremely effectively optimized weight. This frame is made in a glossy style, helping the device add a striking highlight to the design. The feeling when touching the frame is like being covered with a layer of glossy plating around it, so this will not be an easy place to scratch as some users suspect."
},

{
  "id": 4,
  "name": "Lenovo Legion 9 16IRX8 83AG0047VN Gaming Laptop",
  "shortname": "Lenovo Legion9",
  "price": 136000000,
    "ctg_id": 2,
    "product_related_id": 2,
  "img_src": "https://product.hstatic.net/200000722513/product/83ag0047vn_b57e907d045e448b9845f3754b097d5d_grande.png",
  "thumb_src": "https://product.hstatic.net/200000722513/product/83ag0047vn_b57e907d045e448b9845f3754b097d5d_grande.png",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 4,
  "prot_attr_grp_id": 2,
  "supplier_id": 4,
  "discount_id": 4,
  "short_description": "The Lenovo Legion 9 16IRX8 83AG0047VN is meticulously crafted right from its exterior...",
  "description": "The Lenovo Legion 9 16IRX8 83AG0047VN is meticulously crafted right from its exterior. A standout innovation on the Legion 9 is the application of an 8-layer hard pressing method to create a tough and durable shell layer that is 10% more durable than traditional aluminum materials. Premium carbon material makes the newcomer to Lenovo's lineup uniquely distinctive with a lid featuring unique patterns and textures. Liquid cooling technology on the Lenovo Legion 9 laptop brings a revolutionary first in the world. Breakthrough with rapid cooling ability on a premium gaming laptop. Meet the demands of gaming graphics cards and high-intensity work smoothly. Maintain cool operation for gamers to confidently engage in peak gaming. The Lenovo Legion 9 with its powerful configuration including an Intel Core i9-13980HX CPU with 24 cores and 32 threads, 64GB DDR5 RAM operating at 6400MHz speed, and a 2TB M.2 PCIe 4.0x4 NVMe SSD, along with the NVIDIA GeForce RTX 4090 GPU, is a powerhouse. This powerful CPU enables smooth multitasking and high-performance demanding applications. Large and high-speed RAM ensures stable performance while working with multiple applications simultaneously."
},

{
  "id": 17,
  "name": "Laptop ASUS VivoBook Pro 15 OLED K6502VU MA089W",
  "shortname": "ASUS VivoBook Pro 15",
  "price": 42500000,
    "ctg_id": 2,
    "product_related_id": 2,
  "img_src": "https://hanoicomputercdn.com/media/product/71835_vivobook_pro_15_oled_k6502_15.png",
  "thumb_src": "https://hanoicomputercdn.com/media/product/71835_vivobook_pro_15_oled_k6502_15.png",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 17,
  "prot_attr_grp_id": 2,
  "supplier_id": 17,
  "discount_id": 17,
  "short_description": "Asus has just launched a new laptop product for the Asus Vivobook Pro line...",
  "description": "Asus has just launched a new laptop product for the Asus Vivobook Pro line. K6502VU MA089W possesses an inherently luxurious design and powerful configuration of Intel Gen13 CPU with 16GB DDR5, you will definitely be satisfied with the performance it brings. The newest and most modern upgrades such as OLED screen, heating system, new generation connectivity,... are also applied by manufacturers on ASUS VivoBook Pro 15 OLED K6502VU MA089W to upgrade the user experience. common user."
},

{
  "id": 5,
  "name": "Samsung Odyssey NEO G9 LS57CG952 57\" 4K 240Hz Curved Monitor",
  "shortname": "Samsung Neo G9 Curved Monitor",
  "price": 59990000,
    "ctg_id": 2,
    "product_related_id": 2,
  "img_src": "https://product.hstatic.net/200000722513/product/vn-odyssey-neo-g9-g95nc-ls57cg952nexxv-537933911_3923e3e9cf374fafb9ead3a36151d0e4_grande.png",
  "thumb_src": "https://product.hstatic.net/200000722513/product/vn-odyssey-neo-g9-g95nc-ls57cg952nexxv-537933911_3923e3e9cf374fafb9ead3a36151d0e4_grande.png",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 5,
  "prot_attr_grp_id": 2,
  "supplier_id": 5,
  "discount_id": 5,
  "short_description": "The Samsung Odyssey NEO G9 LS57CG952 57 4K 240Hz Curved Monitor brings gaming to life more vividly than reality itself...",
  "description": "The Samsung Odyssey NEO G9 LS57CG952 57 4K 240Hz Curved Monitor brings gaming to life more vividly than reality itself. The world's first Dual UHD monitor envelops your field of view with a super-wide 57-inch screen and a 1000R curvature. Designed to meet the needs of gamers and multimedia enthusiasts alike, this monitor not only delivers stunning visual experiences but also optimizes performance. With a high refresh rate, accurate color display, and integrated eye protection technology, you'll never want to take your eyes off this screen! The power of Quantum Mini-LED and VESA Display HDR IM1000 delivers astonishingly accurate image precision, detail, and brightness at every level. Even the smallest details are incredibly lifelike. Quantum Mini-LED technology helps reproduce more accurate colors and better contrast, providing a vivid and sharp image experience. Meanwhile, VESA Display HDR IM1000 ensures that you can see every detail in scenes of both light and dark, from deep blacks to bright highlights. This not only makes the image more realistic but also allows you to enjoy every moment with optimal brightness."
},


{
  "id": 6,
  "name": "Wrinkle-Free Coffee Fiber Long-Sleeve Shirt WRINKLE FREE 13",
  "shortname": "Wrinkle-Free Shirt WRINKLE FREE 13",
  "price": 327000,
    "ctg_id": 3,
    "product_related_id": 3,
  "img_src": "https://cdn2.yame.vn/pimg/ao-so-mi-tay-dai-soi-ca-phe-wrinkle-free-13-0022478/5dd41ed7-c24b-9500-193e-001ad35b1a68.jpg?w=540&h=756",
  "thumb_src": "https://cdn2.yame.vn/pimg/ao-so-mi-tay-dai-soi-ca-phe-wrinkle-free-13-0022478/5dd41ed7-c24b-9500-193e-001ad35b1a68.jpg?w=540&h=756",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 6,
  "prot_attr_grp_id": 3,
  "supplier_id": 6,
  "discount_id": 6,
  "short_description": "Material: Coffee Fiber (CAFÉ FABRIC)...",
  "description": "Material: Coffee Fiber (CAFÉ FABRIC). Composition: 50% Coffee, 50% Polyester, Odor Control, Fast Drying, Ice Cool Touch, UV Protection"
},


  {
    "id": 7,
    "name": "Men's Premium Slim Fit Cotton Solid Color Chino Pants - 10S24PCA002P",
    "shortname": "Men's Chino Pants 10S24PCA002P",
    "price": 638000,
    "ctg_id": 3,
    "product_related_id": 3,
    "img_src": "https://routine.vn/media/catalog/product/cache/5b5632a96492396f42c72e22fdd64763/q/u/quan-kaki-nam-02-10s24pca002p_black-_7__1_1.jpg",
  "thumb_src": "https://routine.vn/media/catalog/product/cache/5b5632a96492396f42c72e22fdd64763/q/u/quan-kaki-nam-02-10s24pca002p_black-_7__1_1.jpg",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 7,
  "prot_attr_grp_id": 3,
  "supplier_id": 7,
  "discount_id": 7,
    "short_description": "Fit: Slim, Gender: Men, Material: Cotton,...",
    "description": "Fit: Slim, Gender: Men, Material: Cotton, Design: Solid Color, Pocket Style: Slant Pocket"
  },

  {
    "id": 8,
    "name": "Women's Wide Leg Pleated Pocketed Solid Color Fabric Pants - 10S24PFOW002",
    "shortname": "Women's Fabric Pants 10S24PFOW002",
    "price": 569000,
    "ctg_id": 3,
    "product_related_id": 3,
    "img_src": "https://routine.vn/media/amasty/webp/catalog/product/cache/5b5632a96492396f42c72e22fdd64763/q/u/quan-vai-nu-ong-rong-2-10s24pfow002_oyster_gray_1__3_1_jpg.webp",
  "thumb_src": "https://routine.vn/media/amasty/webp/catalog/product/cache/5b5632a96492396f42c72e22fdd64763/q/u/quan-vai-nu-ong-rong-2-10s24pfow002_oyster_gray_1__3_1_jpg.webp",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 8,
  "prot_attr_grp_id": 3,
  "supplier_id": 8,
  "discount_id": 8,
    "short_description": "Fit: Wide Leg, Gender: Women,...",
    "description": "Fit: Wide Leg, Gender: Women, Material: Polyester, Design: Solid Color, Pocket Style: Slant Pocket"
  },

{
  "id": 9,
  "name": "ASUS ROG STRIX RTX4090-O24G GAMING 24GB GDDR6X Graphics Card",
  "shortname": "ASUS RTX4090 24GB",
  "price": 69990000,
    "ctg_id": 2,
    "product_related_id": 2,
  "img_src": "https://lh3.googleusercontent.com/FWmpP-jeT_lyYA40Q9MQqM2nYNueBmejtwAnrOSNriZMuaAjkIYPknqbcr6Ctrk3CQZM34nKnBDY7v3REbhYJEvZCVG873Y=w500-rw",
  "thumb_src": "https://lh3.googleusercontent.com/FWmpP-jeT_lyYA40Q9MQqM2nYNueBmejtwAnrOSNriZMuaAjkIYPknqbcr6Ctrk3CQZM34nKnBDY7v3REbhYJEvZCVG873Y=w500-rw",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 9,
  "prot_attr_grp_id": 2,
  "supplier_id": 9,
  "discount_id": 9,
  "short_description": "Brand: ASUS, Warranty: 36 months...",
  "description": "Brand: ASUS, Warranty: 36 months. Chipset Manufacturer: NVIDIA. Graphics Chip Series: GeForce RTX 40 series. Model: ROG STRIX RTX4090-O24G GAMING. Part-number: 90YV0ID0-M0NM00. GPU: GeForce RTX 4090. Memory: 24GB GDDR6X (21 Gbps / 384-bit). Series: ROG. GPU clock: Boost Clock (OC mode): 2640 MHz."
},

{
  "id": 10,
  "name": "Weilaiya Truffle Multi-Layer Repair Shampoo and Conditioner Set",
  "shortname": "Weilaiya Truffle Shampoo & Conditioner",
  "price": 1170000,
    "ctg_id": 4,
    "product_related_id": 4,
  "img_src": "https://sieuthilamdep.com/images/ab__webp/thumbnails/435/537/detailed/15/bo-dau-goi-xa-phuc-hoi-da-tang-nam-truffle-weilaiya.jpg_jpg.webp",
  "thumb_src": "https://sieuthilamdep.com/images/ab__webp/thumbnails/435/537/detailed/15/bo-dau-goi-xa-phuc-hoi-da-tang-nam-truffle-weilaiya.jpg_jpg.webp",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 10,
  "prot_attr_grp_id": 4,
  "supplier_id": 10,
  "discount_id": 10,
  "short_description": "The Weilaiya Truffle Multi-Layer Repair Shampoo and Conditioner Set is a premium line designed specifically for hair salons...",
  "description": "The Weilaiya Truffle Multi-Layer Repair Shampoo and Conditioner Set is a premium line designed specifically for hair salons. It breaks conventional patterns and establishes a completely new concept of hair care: Shampoo not only cleanses but also rejuvenates and fights aging of the scalp. A healthy scalp is essential for strong and healthy hair. This meticulously crafted set invests in quality, fragrance, color, and packaging. The highlight of this premium product lies in its 'superfood' ingredients, which contain an abundance of nutrients and rare elements that elevate hair and scalp care to a whole new level. Using 'superfoods' in beauty products is a trend among renowned global cosmetics brands."
},

{
  "id": 18,
  "name": "Tresemme Rich Moisture Rich Moisture Shampoo and Conditioner, 28 oz, 2",
  "shortname": "Rich Moisture Shampoo and Conditioner",
  "price": 1720000,
    "ctg_id": 4,
    "product_related_id": 4,
  "img_src": "https://i5.walmartimages.com/seo/Tresemme-Rich-Moisture-Rich-Moisture-Shampoo-and-Conditioner-28-oz-2-Count_52a93c3b-a4a8-4264-97e8-096a9d81ef6f.2c69d6cb75ed84211fee8e8bcc1550e0.jpeg?odnHeight=2000&odnWidth=2000&odnBg=FFFFFF",
  "thumb_src": "https://i5.walmartimages.com/seo/Tresemme-Rich-Moisture-Rich-Moisture-Shampoo-and-Conditioner-28-oz-2-Count_52a93c3b-a4a8-4264-97e8-096a9d81ef6f.2c69d6cb75ed84211fee8e8bcc1550e0.jpeg?odnHeight=2000&odnWidth=2000&odnBg=FFFFFF",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 18,
  "prot_attr_grp_id": 4,
  "supplier_id": 18,
  "discount_id": 18,
  "short_description": "TRESemmé Luxurious Moisture Shampoo and Conditioner Set with Vitamin E,...",
  "description": "TRESemmé Luxurious Moisture Shampoo and Conditioner Set with Vitamin E, There's something about silky hair that's full of natural movement that lets you take on the day with confidence. You can now get that style without having to go to a salon with TRESemme Rich Moisture Shampoo and Conditioner for dry hair. The hydrating shampoo and conditioner are designed to deliver intense hydration to dry strands, leaving your hair with a beautiful, healthy, salon-worthy shine. The result? Gorgeously silky hair that lasts and lasts. These TRESemme shampoos and conditioners are free from Parabens, Mineral Oils, Dyes, and DMDM Hydantoin. How to use the Rich Moisture System: Step 1: Apply the shampoo to wet hair liberally and gently massage the scalp and roots with your fingertips. Step 2: Lightly squeeze the shampoo from roots to ends and rinse thoroughly. Step 3: Repeat steps 1 and 2 with the conditioner."
},

{
  "id": 19,
  "name": "Suave Professionals Invigorating Shampoo and Conditioner Set, Rosemary & Mint, 18 fl oz, 2 Pack",
  "shortname": "Suave Professionals Invigorating Shampoo and Conditioner",
  "price": 4170000,
    "ctg_id": 4,
    "product_related_id": 4,
  "img_src": "https://i5.walmartimages.com/seo/Suave-Professionals-Invigorating-Shampoo-and-Conditioner-Set-Rosemary-Mint-18-fl-oz-2-Pack_61eadb9c-e666-4ffe-9f1f-f9c875541035.5bf0067d6eb5e976a977f16a454e6cc2.jpeg?odnHeight=2000&odnWidth=2000&odnBg=FFFFFF",
  "thumb_src": "https://i5.walmartimages.com/seo/Suave-Professionals-Invigorating-Shampoo-and-Conditioner-Set-Rosemary-Mint-18-fl-oz-2-Pack_61eadb9c-e666-4ffe-9f1f-f9c875541035.5bf0067d6eb5e976a977f16a454e6cc2.jpeg?odnHeight=2000&odnWidth=2000&odnBg=FFFFFF",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 19,
  "prot_attr_grp_id": 4,
  "supplier_id": 19,
  "discount_id": 19,
  "short_description": "New look, same salon-proven quality!...",
  "description": "New look, same salon-proven quality! Suave Rosemary and Mint Invigorating Shampoo and Conditioner for dry, damaged hair feature a silicone-free shampoo that gently cleanses while the conditioner helps detangle for healthy-looking hair. Our rich formulas work to replenish hair to leave it feeling well-nourished and beautiful. This paraben-free shampoo and conditioner are salon-proven to moisturize as well as Aveda Rosemary Mint. Simply lather and rinse with Suave Rosemary and Mint Invigorating Shampoo. Follow by fully coating each hair strand with Suave Rosemary + Mint Invigorating Hair Shampoo and Conditioner for hair that is touchably soft. For best results, use with Suave styling and treatments, which feature hairsprays, serums, and hair masks to help you achieve your desired look. Achieve Salon-Quality Results: Suave hair care is salon-proven to work as well as salon brands."
},

{
  "id": 11,
  "name": "Lolita Round Toe Strap Cross High Heel Platform Shoes PU Leather D1528 White Size 35",
  "shortname": "Lolita High Heel Shoes D1528 White Size 35",
  "price": 627000,
    "ctg_id": 5,
    "product_related_id": 5,
  "img_src": "https://admin.thegioigiay.com/upload/product/2024/05/giay-lolita-mui-tron-quai-ngang-nhun-de-dup-cao-3-5cm-da-pu-d1528-mau-trang-size-35-66336336672f9-02052024165606.jpg",
  "thumb_src": "https://admin.thegioigiay.com/upload/product/2024/05/giay-lolita-mui-tron-quai-ngang-nhun-de-dup-cao-3-5cm-da-pu-d1528-mau-trang-size-35-66336336672f9-02052024165606.jpg",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 11,
  "prot_attr_grp_id": 5,
  "supplier_id": 11,
  "discount_id": 11,
  "short_description": "The Lolita Round Toe Strap Cross High Heel Platform Shoes D1528 are adorable and stylish shoes suitable for girls who love cute and quirky styles...",
  "description": "The Lolita Round Toe Strap Cross High Heel Platform Shoes D1528 are adorable and stylish shoes suitable for girls who love cute and quirky styles. Made from PU leather, these shoes provide softness and comfort to your feet while ensuring durability and easy cleaning. The round toe design and cross strap add a cute and feminine touch to the shoes. The platform sole with a height of 3-5cm adds extra height while maintaining comfort for walking. With their unique and eye-catching style, these shoes are the perfect accent for any of your outfits. Whether you're strolling around the city, going on a date, or attending events, these Lolita shoes will make you stand out and feel confident."
},

{
  "id": 20,
  "name": "SAMBA OG SHOES",
  "shortname": "SAMBA",
  "price": 2627000,
    "ctg_id": 5,
    "product_related_id": 5,
  "img_src": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3bbecbdf584e40398446a8bf0117cf62_9366/Samba_OG_Shoes_White_B75806_01_standard.jpg",
  "thumb_src": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3bbecbdf584e40398446a8bf0117cf62_9366/Samba_OG_Shoes_White_B75806_01_standard.jpg",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 20,
  "prot_attr_grp_id": 5,
  "supplier_id": 20,
  "discount_id": 20,
  "short_description": "Born on the pitch, the Samba is a timeless icon of street style...",
  "description": "Born on the pitch, the Samba is a timeless icon of street style. This silhouette stays true to its legacy with a tasteful, low-profile, soft leather upper, suede overlays and gum sole, making it a staple in everyone's closet - on and off the pitch."
},

{
  "id": 21,
  "name": "ADIDAS STAR WARS SUPERSTAR XLG NANZUKA SHOES",
  "shortname": "ADIDAS STAR NANZUKA",
  "price": 3815000,
    "ctg_id": 5,
    "product_related_id": 5,
  "img_src": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c88898ab72b148ccb2b430b508fbafba_9366/adidas_Star_Wars_Superstar_XLG_Nanzuka_Shoes_White_IF9249_01_standard.jpg",
  "thumb_src": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/c88898ab72b148ccb2b430b508fbafba_9366/adidas_Star_Wars_Superstar_XLG_Nanzuka_Shoes_White_IF9249_01_standard.jpg",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 21,
  "prot_attr_grp_id": 5,
  "supplier_id": 21,
  "discount_id": 21,
  "short_description": "Transport to a galaxy far, far away with the bold proportions and original artwork of these adidas Superstar trainers...",
  "description": "Transport to a galaxy far, far away with the bold proportions and original artwork of these adidas Superstar trainers. They're issued in collaboration with Nanzuka, a Tokyo contemporary art gallery at the intersection of culture and creativity. Featuring exclusive R2-D2 and C-3PO prints from artist Hiroki Tsukuda, they're built with the classic details that make adidas Superstar shoes a forever classic. The synthetic upper and textile lining team up for comfort, while the grippy rubber outsole keeps a solid step. For over 50 years, adidas Superstar sneakers have been the go-to for legends on the court and off. Now the legendary silhouette blasts into hyperspace to bring the Force to you."
},

{
  "id": 12,
  "name": "DSQUARED2 Men's Cyprus Bomber Jacket",
  "shortname": "DSQUARED2 Cyprus Bomber Jacket",
  "price": 57000000,
    "ctg_id": 3,
    "product_related_id": 3,
  "img_src": "https://product.hstatic.net/1000284478/product/900_s74am1411_2_753c819ba2f6481bae6b187d3b698eaf_large.jpg",
  "thumb_src": "https://product.hstatic.net/1000284478/product/900_s74am1411_2_753c819ba2f6481bae6b187d3b698eaf_large.jpg",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 12,
  "prot_attr_grp_id": 3,
  "supplier_id": 12,
  "discount_id": 12,
  "short_description": "Design: Ribbed cuffs and hem...",
  "description": "Design: Ribbed cuffs and hem. Logo detail on the left sleeve. Soft fabric, provides good warmth. Modern color tone, easy to match with various outfits and accessories. Logo: Prominent logo detail on the back. Fit: Comfortable and relaxed fit. Pockets: Two slant pockets. Zipper: Zip closure. Suitable for occasions: Casual outings, work...Seasonal trend: Suitable for all seasons"
},

{
  "id": 13,
  "name": "Gucci GG Supreme Baseball Cap With Feline Head In Neutrals Size M",
  "shortname": "Gucci GG Supreme Baseball Cap",
  "price": 36000000,
    "ctg_id": 6,
    "product_related_id": 6,
  "img_src": "https://cdn.vuahanghieu.com/unsafe/0x500/left/top/smart/filters:quality(90)/https://admin.vuahanghieu.com/upload/product/2023/01/mu-gucci-gg-supreme-supreme-baseball-cap-with-feline-head-in-neutrals-size-m-63b3cdc3a458a-03012023134003.jpg",
  "thumb_src": "https://cdn.vuahanghieu.com/unsafe/0x500/left/top/smart/filters:quality(90)/https://admin.vuahanghieu.com/upload/product/2023/01/mu-gucci-gg-supreme-supreme-baseball-cap-with-feline-head-in-neutrals-size-m-63b3cdc3a458a-03012023134003.jpg",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 13,
  "prot_attr_grp_id": 6,
  "supplier_id": 13,
  "discount_id": 13,
  "short_description": "The cap is made of Canvas/leather material,...",
  "description": "The cap is made of Canvas/leather material, providing a cool and comfortable feeling for the wearer. The stitching of the cap is meticulous and precise, impressing even the most discerning customers. The Gucci logo on the cap creates a very unique focal point. At the back of the cap, you can adjust the size to fit your head circumference. The neutral black color of the cap is easy to match with various outfits according to your preference."
},

{
  "id": 22,
  "name": "STUDDED MEDUSA BASEBALL CAP",
  "shortname": "BASEBALL CAP",
  "price": 15400000,
    "ctg_id": 6,
    "product_related_id": 6,
  "img_src": "https://www.versace.com/dw/image/v2/BGWN_PRD/on/demandware.static/-/Sites-ver-master-catalog/default/dw2e01fa5b/original/90_ICAP004-A236101_A4007_20_Studded~Medusa~Baseball~Cap-Hats~and~Caps-Versace-online-store_1_4.jpg?sw=850&q=85&strip=true",
  "thumb_src": "https://www.versace.com/dw/image/v2/BGWN_PRD/on/demandware.static/-/Sites-ver-master-catalog/default/dw2e01fa5b/original/90_ICAP004-A236101_A4007_20_Studded~Medusa~Baseball~Cap-Hats~and~Caps-Versace-online-store_1_4.jpg?sw=850&q=85&strip=true",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 22,
  "prot_attr_grp_id": 6,
  "supplier_id": 22,
  "discount_id": 22,
  "short_description": "Founded in 1978 by the late Gianni Versace,...",
  "description": "Founded in 1978 by the late Gianni Versace, this Italian design house specializes in sizzling glamour. Gianni’s sister, Donatella Versace, has designed the label since 1997, creating luxuriously sexy dresses and separates. The line also includes shoes and a range of fragrances."
},

{
  "id": 23,
  "name": "Men's Racing Monogram Baseball Cap",
  "shortname": "Monogram Baseball Cap",
  "price": 5600000,
    "ctg_id": 6,
    "product_related_id": 6,
  "img_src": "https://media.neimanmarcus.com/f_auto,q_auto:good,ar_4:5,c_fill,dpr_1.0,w_790/01/nm_4665828_100121_m",
  "thumb_src": "https://media.neimanmarcus.com/f_auto,q_auto:good,ar_4:5,c_fill,dpr_1.0,w_790/01/nm_4665828_100121_m",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 23,
  "prot_attr_grp_id": 6,
  "supplier_id": 23,
  "discount_id": 23,
  "short_description": "Moncler art director, Francesco Ragazzi,...",
  "description": "Moncler art director, Francesco Ragazzi, initially started his Palm Angels project in the form of a much buzzed-about coffee table book featuring black-and-white photography of the LA skateboarding scene, shot by Ragazzi himself. The book published by Rizzoli in 2014 – which featured a foreword written by Pharrell Williams – resulted in a debut ready-to-wear collection for fall/winter 2015. His designs can best be described as assortment of upscale, skate-inspired apparel and accessories, the result of what Ragazzi says happens when he mixes his Italian sartorial background with the laid-back vibes he admires so much in skaters around LA."
},


{
  "id": 14,
  "name": "Initio Parfums Prives Initio Addictive Vibration EDP",
  "shortname": "Initio Parfums Perfume",
  "price": 6787000,
    "ctg_id": 7,
    "product_related_id": 7,
  "img_src": "https://www.thegioinuochoa.com.vn/uploads/item_product/thumb1500x500/202305/230503_200230_186805.png",
  "thumb_src": "https://www.thegioinuochoa.com.vn/uploads/item_product/thumb1500x500/202305/230503_200230_186805.png",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 14,
  "prot_attr_grp_id": 7,
  "supplier_id": 14,
  "discount_id": 14,
  "short_description": "Released in 2016 in France - the capital of the world's top perfumes,...",
  "description": "Released in 2016 in France - the capital of the world's top perfumes, Initio Addictive Vibration EDP is a mesmerizing blend of floral fragrances. Under the hands of Pierre-Constanin Guéros and Maurice Roucel, the scent of Initio Addictive Vibration EDP becomes a beautiful melody with enchanting notes that anyone would want to savor. DESIGN OF INITIO ADDICTIVE VIBRATION EDP\nThe perfume brand Initio Parfums Prives released its first product in 2015, with two collections: Magnetic Blend and Absolutes. Initio Parfums Prives owns fragrances that are elegant and hidden in bottles with simple yet exquisite designs. Initio Addictive Vibration EDP features a traditional design, quite simple, adorned with a powerful, distinctive black coat, creating initial attraction before you immerse yourself in the sweet floral scent. INITIO ADDICTIVE VIBRATION EDP - SWEET FLORAL MELODY\nWhat fragrances does Initio Addictive Vibration EDP have? Initio Addictive Vibration EDP takes us to the atmosphere of spring. The fragrance begins with a combination of orange blossom and apple blossom. If the apple blossom brings a gentle melody, the orange blossom brings a bit of freshness, light sweetness, and vitality. That blend becomes richer thanks to the presence of warm golden honey, the pleasant sweetness of vanilla, and the tranquility of musk, blending seamlessly together. The soft and sweet fragrances blend together, delicately lingering on the skin."
},

{
  "id": 24,
  "name": "PARFUMS DE MARLY",
  "shortname": "MARLY",
  "price": 10787000,
    "ctg_id": 7,
    "product_related_id": 7,
  "img_src": "https://image.harrods.com/parfums-de-marly-sedley-eau-de-parfum-125ml_15661996_28228491_600.jpg",
  "thumb_src": "https://image.harrods.com/parfums-de-marly-sedley-eau-de-parfum-125ml_15661996_28228491_600.jpg",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 24,
  "prot_attr_grp_id": 7,
  "supplier_id": 24,
  "discount_id": 24,
  "short_description": "During the reign of King Louis XV, known as ‘Louis the Beloved’,...",
  "description": "During the reign of King Louis XV, known as ‘Louis the Beloved’, France became the centre of the perfume industry. Recreating the splendour of the Eighteenth Century, Parfums de Marly delivers outstanding fragrances that bear the names of dignified breeds of horses - equestrianism was the pride and glory at King Louis’ fashionable Versailles court, with the King owning over 600 horses including 8 Godolphin and Darly Arabian horses from the King of Tunisia, which he bred with his European breeds to create superior racehorses. Sourced from around the globe, Parfums de Marly’s fine fragrance blends rekindle this very same spirit. Producing male, female and unisex perfumes alongside scented candles, the house’s premium craftsmanship offer ultimate olfactory luxury."
},

{
  "id": 25,
  "name": "CREED",
  "shortname": "CREED",
  "price": 9227000,
    "ctg_id": 7,
    "product_related_id": 7,
  "img_src": "https://image.harrods.com/creed-aventus-eau-de-parfum-100ml_15169217_25801904_800.jpg",
  "thumb_src": "https://image.harrods.com/creed-aventus-eau-de-parfum-100ml_15169217_25801904_800.jpg",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 25,
  "prot_attr_grp_id": 7,
  "supplier_id": 25,
  "discount_id": 25,
  "short_description": "Creed is a go-to for precious,...",
  "description": "Creed is a go-to for precious, artisanal fragrances. Carefully considered in every possible way – from inception and sourcing through to extraction and bottling – the high concentration of natural oils and raw ingredients used sets the tone for a meticulous line-up of scents created by perfumer Olivier Creed and his son, Erwin. Creed’s unique story started with a pair of scented gloves gifted to King George III, and followed with a personal request by Napoleon III and his empress, Eugénie, to relocate to Paris as an official supplier to the royal household. 260 years later, consider a Creed fragrance a step into the Maison’s world of heritage scents; each Creed perfume – Aventus for Her included – is the result of seventh-generation descendent Olivier Creed’s pursuit of what has always been at the fore of the brand's identity: the finest materials."
},


{
  "id": 15,
  "name": "Devialet Gemini II Opera de Paris Earphones",
  "shortname": "Devialet Gemini II Airpods",
  "price": 17890000,
    "ctg_id": 8,
    "product_related_id": 8,
  "img_src": "https://antien.vn/files/styles/pslide/public/products/photos/2023/10/16/tai-nghe-devialet-gemini-ii.jpg?itok=ap4_ESXq",
  "thumb_src": "https://antien.vn/files/styles/pslide/public/products/photos/2023/10/16/tai-nghe-devialet-gemini-ii.jpg?itok=ap4_ESXq",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 15,
  "prot_attr_grp_id": 8,
  "supplier_id": 15,
  "discount_id": 15,
  "short_description": "Adaptive active noise cancellation technology (Devialet Adaptive Noise Cancellation)...",
  "description": "Adaptive active noise cancellation technology (Devialet Adaptive Noise Cancellation). With 10mm titanium drivers.Multi-device connection.Noise-filtering technology on the microphone enhances call quality. Bluetooth 5.2 connectivity. With 5-hour battery life, up to 22 hours combined with the case. Qi wireless charging compatible case. IPX4 water resistance."
},

{
  "id": 26,
  "name": "TAGRY Bluetooth Headphones True Wireless Earbuds",
  "shortname": "TAGRY Bluetooth Headphones",
  "price": 12300000,
    "ctg_id": 8,
    "product_related_id": 8,
  "img_src": "https://images-na.ssl-images-amazon.com/images/I/61uEvVoizoL.jpg",
  "thumb_src": "https://images-na.ssl-images-amazon.com/images/I/61uEvVoizoL.jpg",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 26,
  "prot_attr_grp_id": 8,
  "supplier_id": 26,
  "discount_id": 26,
  "short_description": "LED Power Display and 60H Playback: Dual digital LED...",
  "description": "LED Power Display and 60H Playback: Dual digital LED power display outside of the case is to show the power level for charging case and earbuds. When charging for the case, the LED light will start to flash from 1 to 100. When you put earbuds into the case, then earbuds will start to be charged. 470mAh battery capacity charging case can provide extra 4 times full charging for both earbuds, each earbud can last 6H on single charging. So, you can enjoy 60H music time in total via using in turn."
},

{
  "id": 27,
  "name": "Beats Fit Pro - True Wireless Noise Cancelling Earbuds",
  "shortname": "Beats Fit Pro",
  "price": 14290000,
    "ctg_id": 8,
    "product_related_id": 8,
  "img_src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MK2F3_AV3?wid=1144&hei=1144&fmt=jpeg&qlt=95&.v=1634663483000",
  "thumb_src": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MK2F3_AV3?wid=1144&hei=1144&fmt=jpeg&qlt=95&.v=1634663483000",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 27,
  "prot_attr_grp_id": 8,
  "supplier_id": 27,
  "discount_id": 27,
  "short_description": "What’s in the Box – Beats Fit Pro...",
  "description": "What’s in the Box – Beats Fit Pro True Wireless Noise Cancelling Earbuds; Matching charging case; Eartips with three size options; USB-C to USB-C charging cable; Quick Start Guide; Warranty card. (USB-C power adapter sold separately)"
},

{
  "id": 16,
  "name": "Tissot Men's Watch T086.408.22.036.00 Size 41mm",
  "shortname": "Tissot Men's Watch",
  "price": 19000000,
    "ctg_id": 9,
    "product_related_id": 9,
  "img_src": "https://www.watchstore.vn/images/products/others/2024/large/dong-ho-tissot-t086-408-22-036-00_1-ims-1712565982.webp",
  "thumb_src": "https://www.watchstore.vn/images/products/others/2024/large/dong-ho-tissot-t086-408-22-036-00_1-ims-1712565982.webp",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 16,
  "prot_attr_grp_id": 9,
  "supplier_id": 16,
  "discount_id": 16,
  "short_description": "The Tissot T086.408.22.036.00 is truly a 41mm men's Powermatic 80 Chronometer watch,...",
  "description": "The Tissot T086.408.22.036.00 is truly a 41mm men's Powermatic 80 Chronometer watch, with a thickness of 9.8mm, fitting snugly on the wrists of men with a circumference of 16cm or more. With its silver-tone stainless steel design complemented by gold accents on the bezel, this 3-hand, 1-date watch is extremely suitable for sophisticated gentlemen or confident office workers. The Tissot T086.408.22.036.00 dial is impressive. On the youthful white dial of the watch is an impressive 2-layered face. The central circle features Stick hands and a date window at the familiar 3 o'clock position, making it easy for users to check the date. The outer circle is adorned with 12 diamond hour markers, enhancing the watch's elegant and sophisticated beauty."
},

{
  "id": 28,
  "name": "Orient Mens Analogue Automatic Watch with Stainless Steel Strap RA-AA0003R19B, Silver, 7020-6smd-42mm, Bracelet",
  "shortname": "Orient Mens Analogue Automatic Watch",
  "price": 14500000,
    "ctg_id": 9,
    "product_related_id": 9,
  "img_src": "https://m.media-amazon.com/images/I/61ZB0JH1vVL._AC_SY741_.jpg",
  "thumb_src": "https://m.media-amazon.com/images/I/61ZB0JH1vVL._AC_SY741_.jpg",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 28,
  "prot_attr_grp_id": 9,
  "supplier_id": 28,
  "discount_id": 28,
  "short_description": "Orient rooted nell'artigianalità of its history,...",
  "description": "Orient rooted nell'artigianalità of its history, reliability, precision and elegance resist the passage of time. The historic Japanese brand is the substance of timepieces from durable style, unbeatable quality and affordable price. The goal of Orient has always been to propose unique collections, combining the art of great Japanese watchmakers with a classy design. Orient each collection offers a wide range of watches to choose your own. Concocted to accompany the more energetic lifestyles, Orient sports collection includes advanced features in an attractive design form."
},

{
  "id": 29,
  "name": "Jacob Jensen Men's Quartz Analogue Watch with Rubber Strap Item No. 600",
  "shortname": "Jacob Jensen Men's Quartz Analogue Watch",
  "price": 24100000,
    "ctg_id": 9,
    "product_related_id": 9,
  "img_src": "https://m.media-amazon.com/images/I/71Fm5WNgBVL._AC_SY741_.jpg",
  "thumb_src": "https://m.media-amazon.com/images/I/71Fm5WNgBVL._AC_SY741_.jpg",
  "purchased": 1,
  "quantity": 1,
  "is_featured": 1,
  "is_public": 1,
  "img_id": 29,
  "prot_attr_grp_id": 9,
  "supplier_id": 29,
  "discount_id": 29,
  "short_description": "This is one of the most promising men’s analog timepieces from Jacob Jensen...",
  "description": "This is one of the most promising men’s analog timepieces from Jacob Jensen. Fully protected by a mineral crystal glass, its beautiful dial is housed in a 35mm case. The JJ new 712 watch fits perfectly on the wrist of a manly hand. It vaunts plain hands and a crown for time adjustment. Its case is made of stainless steel and looks very classy. The design of the JACOB JENSEN New Series has been revisited three times since its release in 1995, resulting in some subtle yet significant changes to its design. The inner face of the watch has got a vertical dropped groove, which extenuates its three dimensional quality. It amplifies the illusion of the strap flowing seamlessly around the watch face. The updated models are available in 39 mm, 35 mm and 29 mm watchcases."
}
];

export default DATA_PRODUCT;